### ISSUE TITLE
PipelineException happens when strength 3 is specified and we have constraint group whose size is less than 3.

### ISSUE THREAD

**Issue by mikami-github** [dakusui/jcunit#140]
# Code that causes this issue
```java
@RunWith(JCUnit8.class)
@ConfigureWith(SampleTry.ConfigFactory.class)
public class SampleTry {

	public static class ConfigFactory extends com.github.dakusui.jcunit8.pipeline.stages.ConfigFactory.Base {
		public ConfigFactory() {
		}

		protected Requirement defineRequirement(Requirement.Builder defaultValues) {
			return defaultValues.withStrength(3).build();
		}
	}

	@ParameterSource
	public Parameter.Factory a() {
		return ParameterUtils.simple(1, 2);
	}

	@ParameterSource
	public Parameter.Factory b() {
		return ParameterUtils.simple(1, 2);
	}

	@ParameterSource
	public Parameter.Factory c() {
		return ParameterUtils.simple(1, 2);
	}

	@Condition(constraint = true)
	public boolean aIsGreaterThanB(@From("a") int a, @From("b") int b) {
		return a > b;
	}

	@Test
	public void test(@From("a") int a, @From("b") int b, @From("c") int c) {
		System.out.printf("a=%s,b=%s,c=%s%n", a, b, c);
	}
}
```

# Stacktrace
```
com.github.dakusui.jcunit8.pipeline.PipelineException: Given strength '2' is not in appropriate range (0, 1]

	at com.github.dakusui.jcunit8.exceptions.FrameworkException.checkCondition(FrameworkException.java:22)
	at com.github.dakusui.jcunit8.pipeline.PipelineException.checkIfStrengthIsInRange(PipelineException.java:22)
	at com.github.dakusui.jcunit8.testsuite.SchemafulTupleSet$Builder$1Impl.subtuplesOf(SchemafulTupleSet.java:96)
	at com.github.dakusui.jcunit8.pipeline.stages.Joiner$Standard.computeTuplesToBeCovered(Joiner.java:180)
	at com.github.dakusui.jcunit8.pipeline.stages.Joiner$Standard.doJoin(Joiner.java:114)
	at com.github.dakusui.jcunit8.pipeline.stages.Joiner$Base.apply(Joiner.java:31)
	at com.github.dakusui.jcunit8.pipeline.stages.Joiner$Base.apply(Joiner.java:23)
	at java.util.stream.ReduceOps$2ReducingSink.accept(ReduceOps.java:123)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1235)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:479)
	at com.github.dakusui.jcunit8.pipeline.Pipeline$Standard.engine(Pipeline.java:116)
	at com.github.dakusui.jcunit8.pipeline.Pipeline$Standard.generateTestSuite(Pipeline.java:42)
	at com.github.dakusui.jcunit8.pipeline.Pipeline$Standard.execute(Pipeline.java:35)
	at com.github.dakusui.jcunit8.runners.junit4.JCUnit8.buildTestSuite(JCUnit8.java:218)
	at com.github.dakusui.jcunit8.runners.junit4.JCUnit8.<init>(JCUnit8.java:60)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:49)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

# jcunit version
``0.8.15``

**Comment by dakusui** [comment]
@mikami-github ,
Thanks, I realized that we need to use constraint to reproduce this issue and updated your report accordingly.

**technical note**
This issue is caused if you are trying constraint *C* and a strength *t*, where *C* is belonging to factor group *g* whose size is smaller than *t*.

In this issue, factor *a*  and *b* are grouped into the same group and we call it *G1* and its size is 2. and the other group is *G2* whose sole member is *c*.
But required strength is 3.
For each of *G1* and *G2*, we cannot build a Cartesian product inside it, which is required by generating a covering array.
