### ISSUE TITLE
Cannot translate tuples to sequences

### ISSUE THREAD

**Issue by dakusui** [dakusui/jcunit#80]
Cannot translate tuples to sequences.

```java
Factors:[
  REGEX:aPrefix:alt-2=[Immediate:<World>, Immediate:<WORLD>]
  REGEX:aPrefix:cat-4=[Immediate:<Hello>, Reference:<REGEX:aPrefix:alt-2>]
  REGEX:aPrefix:cat-5=[]
  REGEX:aPrefix:alt-6=[Reference:<REGEX:aPrefix:cat-4>, Reference:<REGEX:aPrefix:cat-5>]
  REGEX:aPrefix:rep-7=[Reference:<REGEX:aPrefix:cat-4>, Reference:<REGEX:aPrefix:alt-6>]
],
TopLevel:[
  [Reference:<REGEX:aPrefix:rep-7>]
]

Hello (World|WORLD) (Hello (World|WORLD)|)

constraint([REGEX:aPrefix:alt-6]->REGEX:aPrefix:alt-2)[REGEX:aPrefix:alt-6, REGEX:aPrefix:alt-2]

java.lang.RuntimeException: REGEX:aPrefix:alt-2 didn't match any of [REGEX:aPrefix:cat-4, REGEX:aPrefix:cat-5] 

	at com.github.dakusui.jcunit.regex.Composer.chooseChild(Composer.java:62)
	at com.github.dakusui.jcunit.regex.Composer.visit(Composer.java:37)
	at com.github.dakusui.jcunit.regex.Expr$Alt.accept(Expr.java:79)
	at com.github.dakusui.jcunit.regex.Composer.visit(Composer.java:47)
	at com.github.dakusui.jcunit.regex.Expr$Cat.accept(Expr.java:69)
	at com.github.dakusui.jcunit.irregex.expressions.ExprTest.compose(ExprTest.java:237)
	at com.github.dakusui.jcunit.irregex.expressions.ExprTest.factorSpaceBuilderRep2(ExprTest.java:163)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:113)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:43)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:239)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)


Process finished with exit code 255
```

**Comment by dakusui** [comment]
Closing since this is not reproducible.
